---
# if fedora then
- include: fedora.yml

- name: install the latest version of vim
  package:
    name: vim
    state: latest

- name: install the latest version of git
  package:
    name: git
    state: latest

- name: install the latest version of acpi
  package:
    name: acpi
    state: latest

- name: install the latest version of xautolock
  package:
    name: xautolock
    state: latest

- name: install the latest version of python
  package:
    name: python
    state: latest

- name: install the latest version of gnome-terminal
  package:
    name: gnome-terminal
    state: latest

- name: install the latest version of powertop
  package:
    name: powertop
    state: latest

- name: install the latest version of xbacklight
  package:
    name: xbacklight
    state: latest

- name: install the latest version of zsh
  package:
    name: zsh
    state: latest

- name: creating workspace
  file:
    path: ~/workspace
    state: directory
    mode: 0750

- name: git pull dotfiles
  git:
    repo: 'https://github.com/djdanielsson/dotfiles.git'
    dest: ~/workspace/dotfiles
    update: no

- name: create .local/share folder
  file:
    path: ~/.local/share/
    state: directory
    mode: 0750

    # fonts still need to be added

- name: git pull Vundle
  git:
    repo: 'https://github.com/gmarik/Vundle.vim.git'
    dest: ~/.vim/bundle/Vundle.vim

- name: checking to see if oh-my-zsh is already installed
  stat:
    path: ~/.oh-my-zsh
  register: DLohmyzsh

- name: downloading the installer for oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: ~/ohmyzsh.sh
    mode: 0750
  when: DLohmyzsh.stat.islnk is not defined

- name: checking for oh-my-zsh installer
  stat:
    path: ~/ohmyzsh.sh
  register: ohmyzsh

- name: Installing oh-my-zsh
  command: /usr/bin/bash ~/ohmyzsh.sh
  when: ohmyzsh.stat.islnk is defined

- name: removing oh-my-zsh installer
  file:
    path: ~/ohmyzsh.sh
    state: absent

- name: create .i3 folder
  file:
    path: ~/.i3
    state: directory
    mode: 0750

- name: checking for .vimrc
  stat:
    path: ~/.vimrc
  register: vimrc

- name: making sure .vimrc is symlink
  file:
    path: ~/.vimrc
    state: absent
  when: vimrc.stat.islnk is defined and vimrc.stat.islnk == False

- name: creating symlink .vimrc
  file:
    src: ~/workspace/dotfiles/.vimrc
    dest: ~/.vimrc
    state: link

- name: Run the vim command to install/update plugins
  command: /usr/bin/vim +PluginInstall +qall
  async: 90
  poll: 5

- name: checking for .bashrc
  stat:
    path: ~/.bashrc
  register: bashrc

- name: making sure .bashrc is symlink
  file:
    path: ~/.bashrc
    state: absent
  when: bashrc.stat.islnk is defined and bashrc.stat.islnk == False

- name: creating symlink .bashrc
  file:
    src: ~/workspace/dotfiles/.bashrc
    dest: ~/.bashrc
    state: link

- name: checking for i3 config
  stat:
    path: ~/.i3/config
  register: i3config

- name: making sure i3 config is symlink
  file:
    path: ~/.i3/config
    state: absent
  when: i3config.stat.islnk is defined and i3config.stat.islnk == False

- name: creating symlink i3 config
  file:
    src: ~/workspace/dotfiles/config
    dest: ~/.i3/config
    state: link

- name: checking for i3 IconicWeather.sh
  stat:
    path: ~/.i3/IconicWeather.sh
  register: i3weather

- name: making sure i3 IconicWeather.sh is symlink
  file:
    path: ~/.i3/IconicWeather.sh
    state: absent
  when: i3weather.stat.islnk is defined and i3weather.stat.islnk == False

- name: creating symlink IconicWeather.sh
  file:
    src: ~/workspace/dotfiles/IconicWeather.sh
    dest: ~/.i3/IconicWeather.sh
    state: link

- name: checking for i3blocks.conf
  stat:
    path: ~/.i3/i3blocks.conf
  register: i3blocks

- name: making sure i3blocks.conf is symlink
  file:
    path: ~/.i3/i3blocks.conf
    state: absent
  when: i3blocks.stat.islnk is defined and i3blocks.stat.islnk == False

- name: creating symlink i3blocks.conf
  file:
    src: ~/workspace/dotfiles/i3blocks.conf
    dest: ~/.i3/i3blocks.conf
    state: link

- name: creating .config/dconf folder
  file:
    path: ~/.config/dconf/
    state: directory
    mode: 0750

- name: checking for gnome terminal settings
  stat:
    path: ~/.config/dconf/user
  register: GTuser

- name: making sure gnome terminal settings are set as symlink
  file:
    path: ~/.config/dconf/user
    state: absent
  when: GTuser.stat.islnk is defined and GTuser.stat.islnk == False

- name: creating symlink user (gnome-terminal settings)
  file:
    src: ~/workspace/dotfiles/user
    dest: ~/.config/dconf/user
    state: link

- name: checking for .zshrc
  stat:
    path: ~/.zshrc
  register: zshrc

- name: making sure .zshrc is symlink
  file:
    path: ~/.zshrc
    state: absent
  when: zshrc.stat.islnk is defined and zshrc.stat.islnk == False

- name: creating symlink .zsh
  file:
    src: ~/workspace/dotfiles/.zshrc
    dest: ~/.zshrc
    state: link

- name: replacing solarized.vim theme to custom
  template:
    src: templates/solarized.vim.j2
    dest: ~/.vim/bundle/vim-airline-themes/autoload/airline/themes/solarized.vim
    mode: 0750


