---
- include: fedora.yml
  when: ansible_os == fedora

- name: install the latest version of vim
  package:
    name: vim
    state: latest

- name: install the latest version of git
  package:
    name: git
    state: latest

- name: install the latest version of acpi
  package:
    name: acpi
    state: latest

- name: install the latest version of xautolock
  package:
    name: xautolock
    state: latest

- name: install the latest version of python3
  package:
    name: python3
    state: latest

- name: install the latest version of npm
  package:
    name: npm
    state: latest

- name: install the latest version of alsa-lib-devel
  package:
    name: alsa-lib-devel
    state: latest

- name: install the latest version of pulseaudio-libs-devel
  package:
    name: pulseaudio-libs-devel
    state: latest

- name: install the latest version of wireless-tools-devel
  package:
    name: wireless-tools-devel
    state: latest

- name: install the latest version of libmpdclient-devel
  package:
    name: libmpdclient-devel
    state: latest

- name: install the latest version of libcurl-devel
  package:
    name: libcurl-devel
    state: latest

- name: install the latest version of gnome-terminal
  package:
    name: gnome-terminal
    state: latest

- name: install the latest version of powertop
  package:
    name: powertop
    state: latest

- name: install the latest version of xbacklight
  package:
    name: xbacklight
    state: latest

- name: install the latest version of zsh
  package:
    name: zsh
    state: latest

- name: install the latest version of dunst
  package:
    name: dunst
    state: latest

- name: install the latest version of podman
  package:
    name: podman
    state: latest

- name: install the latest version of vlc
  package:
    name: vlc
    state: latest

- name: install the latest version of lsof
  package:
    name: lsof
    state: latest

- name: install the latest version of lightdm
  package:
    name: lightdm
    state: latest

- name: install the latest version of nmap
  package:
    name: nmap
    state: latest

- name: install the latest version of ntfs-3g
  package:
    name: ntfs-3g
    state: latest

- name: install the latest version of ntfs-3g-system-compression
  package:
    name: ntfs-3g-system-compression
    state: latest

- name: install the latest version of ntfsprogs
  package:
    name: ntfsprogs
    state: latest

- name: install the latest version of p7zip
  package:
    name: p7zip
    state: latest

- name: install the latest version of p7zip-gui
  package:
    name: p7zip-gui
    state: latest

- name: install the latest version of podman-docker
  package:
    name: podman-docker
    state: latest

- name: install the latest version of rofi-themes
  package:
    name: rofi-themes
    state: latest

- name: creating workspace
  file:
    path: /home/welcome/workspace
    state: directory
    mode: 0750

- name: git pull dotfiles
  git:
    repo: 'https://github.com/djdanielsson/dotfiles.git'
    dest: /home/welcome/workspace/dotfiles
    update: no

- name: create .local/share folder
  file:
    path: /home/welcome/.local/share/
    state: directory
    mode: 0750

    # fonts still need to be added

- name: git pull Vundle
  git:
    repo: 'https://github.com/gmarik/Vundle.vim.git'
    dest: /home/welcome/.vim/bundle/Vundle.vim

- name: checking to see if oh-my-zsh is already installed
  stat:
    path: /home/welcome/.oh-my-zsh
    register: DLohmyzsh

- name: downloading the installer for oh-my-zsh
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /home/welcome/ohmyzsh.sh
    mode: 0750
    when: DLohmyzsh.stat.islnk is not defined

- name: checking for oh-my-zsh installer
  stat:
    path: /home/welcome/ohmyzsh.sh
    register: ohmyzsh

- name: Installing oh-my-zsh
  command: /usr/bin/bash /home/welcome/ohmyzsh.sh
  when: ohmyzsh.stat.islnk is defined

- name: removing oh-my-zsh installer
  file:
    path: /home/welcome/ohmyzsh.sh
    state: absent

- name: checking for .vimrc
  stat:
    path: /home/welcome/.vimrc
    register: vimrc

- name: making sure .vimrc is symlink
  file:
    path: /home/welcome/.vimrc
    state: absent
    when: vimrc.stat.islnk is defined and vimrc.stat.islnk == False

- name: creating symlink .vimrc
  file:
    src: /home/welcome/workspace/dotfiles/.vimrc
    dest: /home/welcome/.vimrc
    state: link

- name: Run the vim command to install/update plugins
  command: /usr/bin/vim +PluginInstall +qall
  async: 90
  poll: 5

- name: checking for .bashrc
  stat:
    path: /home/welcome/.bashrc
    register: bashrc

- name: making sure .bashrc is symlink
  file:
    path: /home/welcome/.bashrc
    state: absent
    when: bashrc.stat.islnk is defined and bashrc.stat.islnk == False

- name: creating symlink .bashrc
  file:
    src: /home/welcome/workspace/dotfiles/.bashrc
    dest: /home/welcome/.bashrc
    state: link

- name: checking for dunst
  stat:
    path: /home/welcome/.config/dunst/dunstrc
    register: dunstrc

- name: making sure dunstrc is symlink
  file:
    path: /home/welcome/.config/dunst/dunstrc
    state: absent
    when: dunstrc.stat.islnk is defined and dunstrc.stat.islnk == False

- name: creating symlink dunst
  file:
    src: /home/welcome/workspace/dotfiles/dunstrc
    dest: /home/welcome/.config/dunst/dunstrc
    state: link

- name: checking for .zshrc
  stat:
    path: /home/welcome/.zshrc
    register: zshrc

- name: making sure .zshrc is symlink
  file:
    path: /home/welcome/.zshrc
    state: absent
    when: zshrc.stat.islnk is defined and zshrc.stat.islnk == False

- name: creating symlink .zsh
  file:
    src: /home/welcome/workspace/dotfiles/.zshrc
    dest: /home/welcome/.zshrc
    state: link

- name: replacing solarized.vim theme to custom
  template:
    src: templates/solarized.vim.j2
    dest: /home/welcome/.vim/bundle/vim-airline-themes/autoload/airline/themes/solarized.vim
    mode: 0750


