---
# defaults file for base
packages:
  - "*"
  - acpi
  - alsa-lib-devel
  - cairo-devel
  - cmake
  - dnf-plugins-core
  - dunst
  - gcc-c++
  - git
  - gnome-terminal
  - i3-gaps
  - i3lock
  - jsoncpp-devel
  - libcurl-devel
  - libmpdclient-devel
  - lightdm
  - lsof
  - nitrogen
  - nmap
  - npm
  - ntfs-3g
  - ntfs-3g-system-compression
  - ntfsprogs
  - p7zip
  - p7zip-gui
  - podman
  - podman-docker
  - powerline-fonts
  - powertop
  - pulseaudio-libs-devel
  - python
  - python3
  - rofi
  - rofi-themes
  - vlc
  - wireless-tools-devel
  - xautolock
  - xbacklight
  - xcb-proto
  - xcb-util-devel
  - xcb-util-wm-devel
  - xcb-util-xrm
  - xcb-util-xrm-devel
  - zsh

home_dir: /home/welcome/
semlinks:
  zshrc:
    file_src: /home/welcome/workspace/dotfiles/.zshrc
    file_dest: /home/welcome/.zshrc
  vimrc:
    file_ src: /home/welcome/workspace/dotfiles/.vimrc
    file_ dest: /home/welcome/.vimrc
  bashrc:
    file_ src: /home/welcome/workspace/dotfiles/.bashrc
    file_ dest: /home/welcome/.bashrc
  dunst:
    file_ src: /home/welcome/workspace/dotfiles/dunstrc
